spring.application.name=quiz-Service
server.port=8090

# PostgreSQL DB connection
spring.datasource.url=jdbc:postgresql://localhost:5432/quizdb
spring.datasource.username=postgres
spring.datasource.password=DiviMuki0409.

# Driver
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Optional (for debugging)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true